template: transmission_cleaner
if:
  - transmission_peers == 0 and transmission_date_added < now - timedelta(days=2): accept
  - transmission_progress == 0 and transmission_date_added < now - timedelta(days=1): accept
transmission:
  action: purge
interval: 12 hours
