template: transmission_cleaner

from_transmission: {}

priority: 20
interval: 6 hours

if:
  - all:
      - transmission_peers == 0
      - transmission_availability < 1.0
      - transmission_date_added < now - timedelta(days=7)
    accept:

  - all:
      - transmission_progress > 0
      - transmission_progress < 100
      - transmission_idle > 604800
    accept:

exec:
  on_accept:
    for_entries: |
      echo "Removing dead torrents: {{title}}"
      echo "  - Progress: {{transmission_progress}}%"
      echo "  - Peers: {{transmission_peers}}"
      echo "  - Inactive days: {{transmission_idle / 86400|int}}"

transmission:
  action: remove
