template: transmission_client
from_transmission: {}
disable: [seen, seen_info_hash, retry_failed]
if:
  - transmission_peers == 0 and transmission_date_active < now - timedelta(hours=24): accept
  - transmission_rate_download == 0 and transmission_date_active < now - timedelta(hours=12): accept
  - transmission_error != '' and transmission_date_added < now - timedelta(hours=6): accept
  - transmission_progress == 0 and transmission_date_added < now - timedelta(hours=48): accept
